# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'paradiseproject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for paradiseproject
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React', path: '../node_modules/react-native', :subspecs => [    
        'Core',
        'RCTActionSheet',
        'RCTAnimation',
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
        'DevSupport'
    ]    

    pod 'GoogleMaps'
    pod 'react-native-maps', path: '../node_modules/react-native-maps/'
    pod 'react-native-google-maps', path: '../node_modules/react-native-maps/'

  target 'paradiseproject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'paradiseprojectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == "react-native-google-maps"
          target.build_configurations.each do |config|
              config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
          end
      end
      if target.name == "React"
        target.remove_from_project
      end
  end
end

# target 'paradiseproject-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for paradiseproject-tvOS

#   target 'paradiseproject-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
